### ISSUE TITLE
Wont download

### ISSUE THREAD

**Issue by ghost** [DemianWright/io_scene_blb#3]
i downloaded it from file and i cant enable it because it doesn't appear there! Help!

**Comment by DemianWright** [comment]
This was indeed an issue with release [2.0.0](https://github.com/DemianWright/io_scene_blb/releases/tag/v2.0.0). It was caused due to Blender not being able to parse a dot character in the directory name. The new [2.1.0](https://github.com/DemianWright/io_scene_blb/releases/tag/v2.1.0) release fixes this issue.
