### ISSUE TITLE
"Upgrade to 2.8x required"

### ISSUE THREAD

**Issue by BlafKing** [DemianWright/io_scene_blb#6]
When I try to use/install the tool in Add-ons of blender I get an error message telling me I need to upgrade to 2.8x
I have tried installing the Add-On on all main 2.8x versions, (2.80, 2.81, 2.82, 2.83)
As well as the latest version of Blender as of right now (2.93) But they all provide the same error message:
![2021-08-29 00_33_19-Blender Preferences](https://user-images.githubusercontent.com/9644716/131232725-18d41737-f1fc-40c9-b83b-3d2ecfbddce1.png)

**Comment by tombon12** [comment]
Issue is fixed by opening __init__.py, finding bl_info which contains the minimum blender version and changing that:
![2021-08-29 02_24_58-● __init__ py - Visual Studio Code](https://user-images.githubusercontent.com/9644716/131234251-aff48bcd-f0b7-431f-96cc-a3b8d7b6fb64.png)
![2021-08-29 02_24_43-__init__ py - Visual Studio Code](https://user-images.githubusercontent.com/9644716/131234247-ee706f60-a2b0-4382-a221-1342b1348bec.png)
